components:
- components:
  - components:
    - event_bindings: {}
      layout_properties: {}
      name: home_btn
      properties: {foreground: 'theme:White', text: Home}
      type: Button
    - event_bindings: {}
      layout_properties: {}
      name: eval_btn
      properties: {foreground: 'theme:White', text: Evaluations}
      type: Button
    - layout_properties: {}
      name: button_3
      properties: {foreground: 'theme:White', text: Profile}
      type: Button
    - event_bindings: {}
      layout_properties: {expand: false, width: 33}
      name: chart_btn
      properties: {foreground: 'theme:White', role: null, text: Charts}
      type: Button
    layout_properties: {width: 960.03528125}
    name: flow_panel_2
    properties: {align: center, background: '#07123b', vertical_align: full, visible: true}
    type: FlowPanel
  layout_properties: {grid_position: 'EAXXBC,VNTPZB'}
  name: flow_panel_1
  properties: {}
  type: FlowPanel
- layout_properties: {grid_position: 'GEUDVN,LYLTOB'}
  name: image_1
  properties: {height: 248.61328125, horizontal_align: center, source: _/theme/Bar_Chart_Target_Line.png}
  type: Image
- layout_properties: {grid_position: 'EXTUXX,BYTYHQ'}
  name: image_2
  properties: {height: 245.18359375, horizontal_align: center, source: _/theme/Screenshot (1175).png}
  type: Image
- layout_properties: {grid_position: 'SVRWLE,KTIPIO'}
  name: image_3
  properties: {height: 200.1875, horizontal_align: center, source: _/theme/Screenshot (1174).png}
  type: Image
container: {type: ColumnPanel}
is_package: true
